### ISSUE TITLE
Save by category and message, not ActiveRecord instance

### ISSUE THREAD

**Issue by ikenfin** [TaronSaribekyan/TsTranslation#1]
Hello! 
I found that this extension works incorrect when i try to use **TsTranslation::save($category, $message)**, it always saves **NULL** in tsy_source_messages table. 

After some research i found this [line](https://github.com/TaronSaribekyan/TsTranslation/blob/master/components/TsTranslation.php#L418), i think that there must be $message, and not null.

Thanks!

**Comment by taronarm** [comment]
Hi Kenny!
**Thank you for advertency.**
Such as _private method_ `_save()` have been created for saving models, which instance of `CActiveRecord`, changes have made in method `TsTranslation::save()`.
If first parameter of method is string (and second parameter also string) it saves as standard message.
You can view changes [here](https://github.com/TaronSaribekyan/TsTranslation/blob/master/components/TsTranslation.php#L315-#L322) .

Thanks!
